### ISSUE TITLE
Evaluation package problem

### ISSUE THREAD

**Issue by DiedeGu** [qualweb/cli#3]
Dear developers, 

thank you for the previous fix. 

Currently when I run with (node v12.18.2):
`qw -f urls.txt`

Or if I run: 
`qw -u https://domain.com -r earl -c` 

The application gives an error. 

I assume `executeACT` function in index.js file from the Evaluation package from Qualweb is not working. 

I base this on the given response response: 
```
Error: Evaluation failed: ReferenceError: ACTRules is not defined
    at __puppeteer_evaluation_script__:2:25  at ExecutionContext._evaluate
Internal (lib/node_modules/@qualweb/cli/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:217:19)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async ExecutionContext.evaluate (lib/node_modules/@qualweb/cli/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:106:16)
    at async Evaluation.executeACT (
(lib/node_modules/@qualweb/cli/node_modules/@qualweb/evaluation/dist/index.js:85:27)
    at async Evaluation.evaluatePage (/@qualweb/cli/node_modules/@qualweb/evaluation/dist/index.js:175:57)
    at async System.runModulesUrl (lib/node_modules/@qualweb/cli/node_modules/@qualweb/core/dist/system.js:113:42)
    at async Promise.all (index 0)
    at async System.execute (/lib/node_modules/@qualweb/cli/node_modules/@qualweb/core/dist/system.js:88:13)
    at async Object.evaluate (ib/node_modules/@qualweb/cli/node_modules/@qualweb/core/dist/index.js:19:5)
    at async cli (/lib/node_modules/@qualweb/cli/dist/index.js:29:25)
```

(If i run `qw -u https://domain.com -c` or `qw -u https://domain.com -r earl` there are no problems)

**Comment by DiedeGu** [comment]
Update, the first url was: 
`domain.com/sitemap.xml`. 

When this was removed the `-f urls.txt` does run and generate a report.

**Comment by carlosapaduarte** [comment]
@DiedeGu are you sure you're using the latest version of qw cli?
I cannot replicate an error with `qw -u https://domain.com -r earl -c` (it executes and compiles the evaluation report)

Regarding the error when using a file to specify the urls: qualweb does not evaluate XML files. That explains the error. We will update to catch the error and throw it.

**Comment by DiedeGu** [comment]
@carlosapaduarte You were right, I cant reproduce it either. I think I must have ran `qw -f urls.txt with -r earl -c` , sorry for the mixup.
